produce useful exit message if ambigious match is found. Without it it does the following: ``` $HOME/netshow/netshow-clsupport-lib/.tox/py27/bin/netshow  b
ERROR: ambiguous parse chain...matches:
bridges [all] [--mac|-m] [--oneline|-1|--json|-j]
0: REQUIRED: True, KEY_TEXT: bridges, VALUE: True, WORDS: ['bridges']
1: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['all']
2: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--mac', '-m']
3: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--oneline', '-1',
'--json', '-j']

bonds [all] [--mac|-m] [--oneline|-1|--json|-j]
0: REQUIRED: True, KEY_TEXT: bonds, VALUE: True, WORDS: ['bonds']
1: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['all']
2: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--mac', '-m']
3: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--oneline', '-1',
'--json', '-j']

bondmems [all] [--mac|-m] [--oneline|-1|--json|-j]
0: REQUIRED: True, KEY_TEXT: bondmems, VALUE: True, WORDS: ['bondmems']
1: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['all']
2: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--mac', '-m']
3: REQUIRED: False, KEY_TEXT: None, VALUE: False, WORDS: ['--oneline', '-1',
'--json', '-j']

Usage:
    netshow counters [errors] [all] [--json | -j ]
    netshow lldp [--json | -j ]
    netshow system [--json | -j ]
    netshow interface [<iface>] [all] [--mac | -m ] [--oneline | -1 | --json |
-j ]
    netshow access [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow bridges [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow bonds [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow bondmems [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow mgmt [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow l2 [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow l3 [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow phy [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow trunks [all] [--mac | -m ] [--oneline | -1  | --json | -j]
    netshow (--version | -V)

```

with the patch

```
$HOME/netshow/netshow-clsupport-lib/.tox/py27/bin/netshow  b
Ambigious Match. Options: bridges, bonds, bondmems

```